// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Levi9.Cinema.Api.Database.Migrations.PostgreSql
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Levi9.Cinema.Api.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe9ad1d6-b24f-4861-85ff-8a45e7bd92d0"),
                            Cover = "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
                            Rating = 0f,
                            Status = 0,
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = new Guid("06279b27-fb0c-4068-9316-a11d6e4fb1a8"),
                            Cover = "https://www.slashfilm.com/wp/wp-content/images/International-Avengers-Age-of-Ultron-Poster-700x989.jpg",
                            Rating = 0f,
                            Status = 0,
                            Title = "The Avengers: Age of Ultron movie poster"
                        },
                        new
                        {
                            Id = new Guid("a51806e9-1f90-49fb-b17d-fbde83e5792a"),
                            Cover = "https://media.vanityfair.com/photos/592592596736887ada186bcd/master/w_1600%2Cc_limit/spider-man-homecoming-SMH_DOM_Online_FNL_1SHT_3DRD3DIMX_AOJ_300dpi_01_rgb.jpg",
                            Rating = 0f,
                            Status = 0,
                            Title = "Spider-man: Home Coming"
                        },
                        new
                        {
                            Id = new Guid("7447d117-9c70-4b2e-af65-fc12e8634770"),
                            Cover = "https://m.media-amazon.com/images/I/713KEd-8jyL._AC_SL1500_.jpg",
                            Rating = 0f,
                            Status = 0,
                            Title = "Harry Potter and The Philosopher's Stone"
                        },
                        new
                        {
                            Id = new Guid("c1ee1710-bc34-48be-aa3a-b060750dbc9d"),
                            Cover = "https://lumiere-a.akamaihd.net/v1/images/swtlj_imax_oversize_1-sht_v6_lg_d4edae12.jpeg?region=0%2C0%2C827%2C1200",
                            Rating = 0f,
                            Status = 0,
                            Title = "Star Wars: The Last Jedi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
